- alias: "Remind everyone when bins need to go out"
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: ifttt.trigger
      data_template: 
        event: "ha_voip_message"
        value1: "Hi everyone. Just a reminder that the {{ states('sensor.garbage_type') }} bins need to be taken out before you head to bed tonight."
