- alias: "Turn on Night Vision when Living Room camera can't see"
  trigger:
    platform: numeric_state
    entity_id: sensor.ip_webcam_light_level
    below: 1
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.ip_webcam_night_vision
- alias: "Turn off Night Vision when Living Room camera gets light"
  trigger:
    platform: numeric_state
    entity_id: sensor.ip_webcam_light_level
    above: 1
  condition:
    condition: sun
    after: sunrise
    after_offset: "-1:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.ip_webcam_night_vision
