- alias: "Automatically wake up Simon with the briefing"
  trigger:
    - platform: state
      entity_id: sensor.asleep_simon
  action:
    service: script.turn_on
    entity_id: script.morningbriefing_simon
