- alias: "Turn Simon's things off when he leaves"
  trigger:
    platform: state
    entity_id: device_tracker.simon_iphone
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.simonsroom
        state: 'on'
      - condition: time
        after: '08:00:00'
        before: '22:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.simonsroom
    - service: notify.ios_simons_iphone
      data_template:
        message: "Your devices were automatically switched off."
