########
# HOME #
########

- alias: "Turn things on when I get home"
  trigger:
    platform: state
    entity_id: input_select.simon_presence
    from: "Away"
    to: "Home"
  action:
    - service: homeassistant.turn_on
      entity_id: light.simons_bedroom
    - service: homeassistant.turn_on
      entity_id: switch.mac_display
    - condition: numeric_state # If it's warm/hot outside, make sure the fan is on
      entity_id: sensor.bom_bendigo_air_temp_c
      above: 25
    - service: homeassistant.turn_on
      entity_id: switch.fan

########
# AWAY #
########

- alias: "Turn things off when I leave"
  trigger:
    platform: state
    entity_id: input_select.simon_presence
    to: "Away"
  action:
    - service: homeassistant.turn_off
      entity_id: group.simonsbedroom
    - service: homeassistant.turn_off
      entity_id: switch.mac_display

- alias: "Preheat the bedroom when I leave work, if needed"
  trigger:
    platform: state
    entity_id: input_select.simon_presence
    from: "At Work"
    to: "Away"
  condition:
    condition: numeric_state
    entity_id: sensor.bom_bendigo_air_temp_c
    below: 11
  action:
    - service: homeassistant.turn_on
      entity_id: switch.heater