- alias: "Simon home? Turn bedroom light on after dark"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    - service: light.turn_on
      entity_id: light.simon
      data:
        transition: 1800 # 30 minutes
        brightness_pct: 100
    - service: notify.discord
      data:
        message: "Your lights are fading in, because the sun is now setting."
        target: 375206372574363660

- alias: "Prepare room for bedtime"
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: light.turn_on
      entity_id: light.simon
      data:
        transition: 120 # 2 minutes
        brightness_pct: 1
    - service: switch.turn_on
      entity_id: switch.simons_heater
    - service: notify.discord
      data:
        message: "Your room is preparing for when you head to bed, because it's now 9PM."
        target: 375206372574363660
