- alias: "Simon home? Turn bedroom light on after dark"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    - service: light.turn_on
      entity_id: light.simons_bedroom
      data:
        transition: 1800 # 30 minutes
        brightness_pct: 100
    - service: notify.discord
      data:
        message: "Your lights are fading in, because the sun is now setting."
        target: 375206372574363660
