- alias: "Simon home? Turn bedroom light on after dark"
  trigger:
    platform: sun
    event: sunset
    offset: "01:00:00"
  condition:
    condition: state
    entity_id: device_tracker.simon_iphone
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: light.simons_bedroom
- alias: "Simon home? Wake up with bedroom lights"
  trigger:
    platform: sun
    event: sunrise
    offset: "-01:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.simonsiphone
        state: home
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
    service: light.turn_on
    entity_id: light.simons_bedroom
    data:
      transition: 3600 # 1 hour
      brightness_pct: 100
