- alias: "Simon home? Turn bedroom light on after dark"
  trigger:
    platform: sun
    event: sunset
    offset: "01:00:00"
  condition:
    condition: state
    entity_id: device_tracker.simon_angler
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: light.simons_bedroom
- alias: Simon's Bedroom Light - Adjust Brightness
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.bedroom_brightness
  action:
    - service: light.turn_on
# Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.simons_bedroom
        brightness: '{{ trigger.to_state.state | int }}'
