- alias: "Simon home? Turn bedroom light on after dark"
  trigger:
    platform: sun
    event: sunset
    offset: "01:00:00"
  condition:
    condition: state
    entity_id: device_tracker.simonsiphone
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: light.simons_bedroom
- alias: "Simon home? Wake up with bedroom lights"
  trigger:
    platform: time
    after: '07:00:00'
  condition:
    condition: state
    entity_id: device_tracker.simonsiphone
    state: home
  action:
    service: light.turn_on
    entity_id: light.simons_bedroom
    data:
      transition: 1800
      brightness_pct: 100
