# Docker switch alerts
- alias: "Alert Simon when Bucket has updated its state"
  trigger:
    - platform: state
      entity_id: switch.docker_bucket
  action:
    service: notify.discord
    data_template:
      message: "*Bucket was switched {{ states('switch.docker_bucket') }}*\n{% if is_state('switch.docker_bucket', 'off') %}*This usually shouldn't happen. Bucket might be updating, otherwise <@49288117307310080> should check Docker's console.*{% endif %}"
      target: 