- alias: Study Light - Adjust Brightness
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.study_brightness
  action:
    - service: light.turn_on
# Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.study
        brightness: '{{ trigger.to_state.state | int }}'
