# This config uses:
# Custom-UI by @andrey-git
# ha-history-stats by @bokub

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret loc_lat
  longitude: !secret loc_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret loc_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  customize_glob: !include customize.yaml

customizer:
  panel: true
  hide_customui_attributes: false
  hide_attributes:
    - node_id
    - value_index

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret url
  ssl_certificate: /Users/simonsays/fullchain.pem
  ssl_key: /Users/simonsays/privkey.pem

recorder:
  purge_days: 7
  exclude:
    domains:
      - automation
      - weblink
      - updater


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.external_ip

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ios:

mqtt:
  broker: 127.0.0.1

camera:
  - platform: generic
    still_image_url: http://www.bom.gov.au/radar/IDR023.gif?{{ now().strftime("%Y%m%d%H%M") }}00
    name: Rain Radar
    limit_refetch_to_url_change: true

wemo:
  static:
    - 192.168.0.100
    - 192.168.0.101

# Various Location Tracking

device_tracker:
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass

media_player: !include_dir_merge_list cfg/media
binary_sensor: !include_dir_merge_list cfg/sensors_binary/
sensor: !include_dir_merge_list cfg/sensors/
switch: !include_dir_merge_list cfg/switches/

notify:
  - name: discord
    platform: discord
    token: !secret discord_token

group: !include_dir_merge_named cfg/groups/
automation: !include_dir_merge_list cfg/auto/

weblink:
  entities:
    - name: Router
      url: http://192.168.0.1/
    - name: Home Assistant
      url: https://home-assistant.io
    - name: Sonarr
      url: http://192.168.0.60:8909
    - name: Cardigann
      url: http://192.168.0.60:5060
    - name: Jackett
      url: http://192.168.0.60:5117

shell_command:
  livestream: livestreamer --twitch-oauth-token gn4dfwud6on2x446oith2pon3sso5g {{url}} 720p --player-passthrough hls -p castnow -a '"{filename}" --device "{{device}}" --exit'

input_select: !include_dir_merge_named cfg/input_select/

script: !include_dir_merge_named cfg/scripts/

wake_on_lan:

apiai:
intent_script: !include_dir_merge_named cfg/intents
