# This config uses:
# Custom-UI by @andrey-git
# ha-history-stats by @bokub

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret loc_lat
  longitude: !secret loc_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret loc_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  customize_glob: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ios:

wemo:
  static:
    # Turns out these still need to be detected manually, so giving them fixed IPs
    - 192.168.1.90
    - 192.168.1.91

android_ip_webcam:
  - host: 192.168.1.2
    port: 2244
    sensors:
      - battery_level
      - light
      - motion
    switches:
      - exposure_lock
      - focus
      - night_vision
      - torch
      - whitebalance_lock

# Various Location Tracking

device_tracker:
  - platform: gpslogger
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1/24
      - 127.94.0.1
      - 239.0.0.250
    exclude:
      - 192.168.1.1 # Router
      - 192.168.1.40 # Server
      - 192.168.1.8 # AppleTV
      - 192.168.1.20 # Wifi Repeater

zone:
  - name: Home
    latitude: !secret loc_lat
    longitude: !secret loc_lon
    radius: 150
  - name: Boris Murgers
    latitude: !secret loc_boris_lat
    longitude: !secret loc_boris_lon
    icon: mdi:briefcase
    passive: true
  - name: Parents
    latitude: !secret loc_parents_lat
    longitude: !secret loc_parents_lon
    icon: mdi:castle

media_player: !include_dir_merge_list cfg/media

binary_sensor: !include_dir_merge_list cfg/sensors_binary/

sensor: !include_dir_merge_list cfg/sensors/

switch: !include_dir_merge_list cfg/switches/

notify:
  - platform: joaoapps_join
    api_key: !secret join_api
    device_id: !secret join_device
  - platform: discord
    name: simonprivate
    token: !secret discord_token

joaoapps_join:
  - name: android
    device_id: group.android
    api_key: !secret join_api

group: !include_dir_merge_named cfg/groups/

automation: !include_dir_merge_list cfg/auto/

weblink:
  entities:
    - name: Router
      url: http://192.168.1.1/
    - name: Home Assistant
      url: https://home-assistant.io
    - name: Sonarr
      url: http://192.168.1.6:8909
    - name: Cardigann
      url: http://192.168.1.6:5060
    - name: Jackett
      url: http://192.168.1.6:5117
scene:
  - name: Goodnight Simon
    entities:
      switch.heater_switch: on
      light.simons_bedroom:
        state: on
        brightness: 10

input_select: !include_dir_merge_named cfg/input_select/
script: !include_dir_merge_named cfg/scripts/
