- platform: command_line
  switches:
    discord_bucket:
      command_on: forever start -c $(which python3) /opt/bucket/Red-DiscordBot/launcher.py --start
      command_off: forever stop /opt/bucket/Red-DiscordBot/launcher.py
      command_state: forever list | grep /opt/bucket/Red-DiscordBot/launcher.py
      friendly_name: Bucket (Tedbeet)
    discord_neubott:
      command_on: forever start -c $(which python3) /opt/neubott/Red-DiscordBot/launcher.py --start
      command_off: forever stop /opt/neubott/Red-DiscordBot/launcher.py
      command_state: forever list | grep /opt/neubott/Red-DiscordBot/launcher.py
      friendly_name: Neubott (Neutopia)
