- platform: template
  sensors: 
    pc_simon: # Desktops
      friendly_name: "Simon's PC"
      value_template: " {{ states.device_tracker.simonswindows.state == 'home' }} "
      entity_id: device_tracker.simonswindows
    pc_simonmac:
      friendly_name: "Simon's Mac Mini"
      value_template: " {{ states.device_tracker.simonsays.state == 'home' }} "
      entity_id: device_tracker.simonsays
    pc_beth:
      friendly_name: "Beth's PC"
      value_template: " {{ states.device_tracker.bethpc.state == 'home' }} "
      entity_id: device_tracker.bethpc
    pc_matt:
      friendly_name: "Matt's PC"
      value_template: " {{ states.device_tracker.desktop11ft84o.state == 'home' }} "
      entity_id: device_tracker.desktop11ft84o
    pc_jono:
      friendly_name: "Jono's PC"
      value_template: " {{ states.device_tracker.jonopc.state == 'home' }} "
      entity_id: device_tracker.jonopc
    pc_izzy:
      friendly_name: "Izzy and Michele's PC"
      value_template: " {{ states.device_tracker.izzypc.state == 'home' }} "
      entity_id: device_tracker.izzypc
    laptop_mum:
      friendly_name: "Michele's Laptop"
      value_template: " {{ states.device_tracker.laptop0blatqnt.state == 'home' }} "
      entity_id: device_tracker.laptop0blatqnt
    # --- #
    console_wiiu: # Console
      friendly_name: "Wii U"
      value_template: " {{ states.device_tracker.nintendo_wii_u.state == 'home' }} "
      entity_id: device_tracker.nintendo_wii_u
    console_ps4:
      friendly_name: "Playstation 4"
      value_template: " {{ states.device_tracker.sony_playstation_4.state == 'home' }} "
      entity_id: device_tracker.sony_playstation_4
    console_xb1:
      friendly_name: "Xbox One"
      value_template: " {{ states.device_tracker.xboxone.state == 'home' }} "
      entity_id: device_tracker.xboxone
    3ds_simon:
      friendly_name: "Simon's Nintendo 3DS"
      value_template: " {{ states.device_tracker.simons_nintendo_3ds.state == 'home' }} "
      entity_id: device_tracker.simons_nintendo_3ds