- platform: ping
  host: 192.168.1.40
  name: Simon's Mac Mini
- platform: ping
  host: 192.168.1.3
  name: Epson WF-3640 Multifunction Printer
- platform: ping
  host: 192.168.1.5
  name: Cassie's PC
- platform: ping
  host: 192.168.1.17
  name: Martin's Laptop
- platform: ping
  host: 192.168.1.41
  name: Simon's Windows PC
