# Whatpulse - Mouse/Keyboard usage tracking

- platform: rest
  resource: http://api.whatpulse.org/user.php?format=json&user=neurario
  value_template: '{{ value_json.Keys }}'
  name: Whatpulse - Keys Pressed
  unit_of_measurement: Keys
- platform: rest
  resource: http://api.whatpulse.org/user.php?format=json&user=neurario
  value_template: '{{ value_json.Clicks }}'
  name: Whatpulse - Mice Clicked
  unit_of_measurement: Clicks
