- platform: history_stats
  name: Heater Runtime Today
  entity_id: switch.heater_switch
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
