- platform: template
  sensors:
    batt_iphone:
      friendly_name: iPhone Battery
      unit_of_measurement: "%"
      value_template: >-
            {%- if states.device_tracker.lilyflavellesiphone.attributes.battery %}
                {{ states.device_tracker.lilyflavellesiphone.attributes.battery|round }}
            {% else %}
                ???
            {%- endif %}
    batt_watch:
      value_template: >-
            {%- if states.device_tracker.simonsapple_watch.attributes.battery %}
                {{ states.device_tracker.simonsapple_watch.attributes.battery|round }}
            {% else %}
                ???
            {%- endif %}
      friendly_name: Simon's Apple Watch Battery
      unit_of_measurement: "%"
    batt_ipad:
      value_template: >-
            {%- if states.device_tracker.simonflavellesipad.attributes.battery %}
                {{ states.device_tracker.simonflavellesipad.attributes.battery|round }}
            {% else %}
                ???
            {%- endif %}
      friendly_name: Simon's iPad Battery
      unit_of_measurement: "%"
