- platform: template
  sensors:
    simon_iphonebattery:
      friendly_name: Simon's iPhone Battery
      unit_of_measurement: "%"
      value_template: >-
            {%- if states.device_tracker.simon_iphone.attributes.battery %}
                {{ states.device_tracker.simon_iphone.attributes.battery|round }}
            {% else %}
                ???
            {%- endif %}
    simon_ipadbattery:
      value_template: >-
            {%- if states.device_tracker.simon_ipad.attributes.battery %}
                {{ states.device_tracker.simon_ipad.attributes.battery|round }}
            {% else %}
                ???
            {%- endif %}
      friendly_name: Simon's iPad Battery
      unit_of_measurement: "%"
