- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: memory_free
    - type: disk_free
      arg: /Volumes/Media HD
    - type: disk_free
      arg: /

- platform: glances
  host: 192.168.1.41
  resources:
    - 'disk_free'
    - 'memory_free'
    - 'swap_free'
    - 'processor_load'
    - 'process_running'
    - 'cpu_temp'
