- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: memory_free
    - type: disk_free
      arg: /Volumes/Media HD
    - type: disk_free
      arg: /
